### Test GET
GET http://localhost:3000/contacts/
Content-Type: application/json

### Test GET single
GET http://localhost:3000/contacts/67ccb6c3fcb866804bb2ab1e
Content-Type: application/json

### Teste POST
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Roseane",
    "lastName": "Trindade",
    "email": "roseanetrindade@gmail.com",
    "favoriteColor": "pink",
    "birthday": "1999-04-10"
}

### Test PUT
PUT http://localhost:3000/contacts/67ccb6c3fcb866804bb2ab1e
Content-Type: application/json

{
    "firstName":"Stephany",
    "lastName":"Lopes",
    "email":"stephanylopes434@gmail.com",
    "favoriteColor":"turquoise",
    "birthday":"1999-04-18"
}

### Test DELETE
DELETE http://localhost:3000/contacts/67d37d3ea1e0c863d40363cf
Content-Type: application/json
